version: '3.7'
services:
  webserver:
    image: nginx:alpine
    container_name: hanze-web
    hostname: hanze.eu
    restart: unless-stopped
    depends_on:
      - LaravelWebApp
    ports:
      - 80:80
      - 443:443
    networks:
      - hanze
    volumes:
      - ${PWD}/:/var/www/html
      - ${PWD}/docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ${PWD}/docker/nginx/certs:/etc/ssl/
  LaravelWebApp:
    build:
      context: ./docker
      dockerfile: PHP8LaravelDockerFile
    container_name: hanze-app
    hostname: webapp
    image: foxoffire33/php8laravel8
    working_dir: '/var/www/html'
    depends_on:
      - mariadb
    volumes:
      - ${PWD}/:/var/www/html
      #- ${PWD}/docker/php:/usr/local/etc/php/conf.d/
    networks:
      - hanze
    healthcheck:
      test: [ "CMD", "php", "-v" ]
  LaravelWorker:
    container_name: hanze-yworker
    hostname: hanzeworker
    image: foxoffire33/php8laravel8
    working_dir: '/var/www/html'
    command: "php artisan queue:work"
    depends_on:
      - redis
    volumes:
      - ${PWD}/:/var/www/html
    networks:
      - hanze
  mariadb:
    image: 'mariadb'
    container_name: hanze-database
    hostname: database
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ${PWD}/docker/mysql:/var/lib/mysql
    networks:
      - hanze
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
  redis:
    image: redis:alpine
    container_name: hanzeredis
    hostname: redis
    volumes:
      - ${PWD}/docker/redis:/data
    networks:
      - hanze
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
networks:
  hanze:
    driver: bridge
