version: '3.7'
services:
  webserver:
    image: nginx:alpine
    container_name: hanze-web
    hostname: hanze.eu
    restart: unless-stopped
    depends_on:
      - LaravelWebApp
    ports:
      - 8080:80
    networks:
      - hanze
    volumes:
      - ${PWD}/:/var/www/html
      - ${PWD}/docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ${PWD}/docker/nginx/certs:/etc/ssl/
  LaravelWebApp:
    build:
      context: ./docker
      dockerfile: PHP8LaravelDockerFile
    container_name: webapp
    hostname: webapp
    image: foxoffire33/php8laravel8
    working_dir: '/var/www/html'
    depends_on:
      - mariadb
    volumes:
      - ${PWD}/:/var/www/html
      #- ${PWD}/docker/php:/usr/local/etc/php/conf.d/
    networks:
      - hanze
    healthcheck:
      test: [ "CMD", "php", "-v" ]
  mariadb:
    image: 'mariadb'
    container_name: hanze-database
    hostname: database
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ${PWD}/docker/mysql:/var/lib/mysql
    networks:
      - hanze
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
networks:
  hanze:
    driver: bridge
