openapi: 3.0.3
info:
  title: Lumen
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: 'Lumen (9.0.0) (Laravel Components ^9.0)'
      tags:
        - Endpoints
      security: []
  /authentication:
    post:
      summary: 'Basic login'
      description: 'This is used for first time authentication.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n \"token\": \"String\"\n}\n @response 401 \"error\": {\n \"code\": 401,\n \"message\": \"Invalid credentials.\"\n}"
        429:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "error\": {\n \"code\": 429,\n \"message\": \"Too Many Attempts.\"\n}"
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'E-mail of the user.'
                  example: development@dxmusic.nl
                password:
                  type: string
                  description: 'Password of the user.'
                  example: debitis
              required:
                - email
                - password
      security: []
  /authentication/jwt:
    get:
      summary: 'Renew token'
      description: 'With this endpoint you can request an new token, the current one should be valid.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n \"token\": \"String\"\n}\n @response 401 \"error\": {\n \"code\": 401,\n \"message\": \"Unauthorized.\"\n}"
        429:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "error\": {\n \"code\": 429,\n \"message\": \"Too Many Attempts.\"\n}"
      tags:
        - Endpoints
tags:
  -
    name: Endpoints
    description: ''
